/**
 * Unified Transaction Detection Service - Type Definitions
 * Shared types across all ingestion sources and processing engines
 */

export type Platform = 'iOS' | 'Android';
export type SourceType = 'SMS' | 'Notification' | 'Email' | 'Manual';
export type TransactionIntent = 'Credit' | 'Debit' | 'Transfer' | 'Ignore';
export type TransactionType = 'income' | 'expense' | 'transfer';

/**
 * Unified Message Interface
 * All ingestion sources MUST output this format
 */
export interface UnifiedMessage {
  /** Raw message text */
  rawText: string;
  
  /** Source type (SMS, Notification, Email, Manual) */
  sourceType: SourceType;
  
  /** Message timestamp */
  timestamp: Date;
  
  /** Sender identification (phone number, app name, email, etc.) */
  senderIdentifier: string;
  
  /** Platform (iOS or Android) */
  platform: Platform;
  
  /** Confidence hint from source (0-1) */
  confidenceHint: number;
  
  /** Additional metadata from source */
  metadata?: Record<string, any>;
}

/**
 * Normalized Message after noise filtering
 */
export interface NormalizedMessage extends UnifiedMessage {
  /** Cleaned text with noise removed */
  cleanText: string;
  
  /** Original raw text preserved */
  originalRawText: string;
  
  /** Processing metadata */
  processingMetadata: {
    noiseRemoved: string[];
    normalizations: string[];
  };
}

/**
 * Detected Transaction Candidate
 */
export interface TransactionCandidate {
  /** Unique identifier for this candidate */
  id: string;
  
  /** Original message */
  message: NormalizedMessage;
  
  /** Detected transaction intent */
  intent: TransactionIntent;
  
  /** Confidence score (0-1) */
  confidenceScore: number;
  
  /** Extracted transaction fields */
  extractedData: ExtractedTransactionData;
  
  /** Extraction details for debugging */
  extractionDetails: ExtractionDetails;
  
  /** Classification result */
  classification?: TransactionClassification;
  
  /** Processing timestamp */
  processedAt: Date;
}

/**
 * Extracted Transaction Data Fields
 */
export interface ExtractedTransactionData {
  /** Transaction type */
  type: TransactionType | null;
  
  /** Amount in base currency */
  amount: number | null;
  
  /** Currency code (e.g., 'INR', 'USD') */
  currency: string | null;
  
  /** Transaction date */
  date: Date | null;
  
  /** Bank or provider name */
  bankOrProvider: string | null;
  
  /** Account identifier (if available) */
  accountIdentifier: string | null;
  
  /** Reference number or transaction ID */
  referenceNumber: string | null;
  
  /** Transaction description */
  description: string | null;
  
  /** Recipient/Sender name (for transfers) */
  counterparty: string | null;
}

/**
 * Extraction Details for Debugging
 */
export interface ExtractionDetails {
  /** Which patterns matched */
  matchedPatterns: string[];
  
  /** Regex matches for debugging */
  patternMatches: Record<string, any>;
  
  /** Field extraction scores */
  fieldScores: Record<keyof ExtractedTransactionData, number>;
  
  /** Overall extraction confidence */
  overallConfidence: number;
  
  /** Extraction errors or warnings */
  warnings: string[];
}

/**
 * Transaction Classification Result
 */
export interface TransactionClassification {
  /** Classified transaction type */
  type: TransactionType;
  
  /** Suggested category ID */
  suggestedCategoryId: string | null;
  
  /** Category name */
  categoryName: string | null;
  
  /** Classification confidence */
  confidence: number;
  
  /** Auto-generated flag */
  isAutoGenerated: boolean;
  
  /** Classification metadata */
  metadata: Record<string, any>;
}

/**
 * Duplicate Detection Result
 */
export interface DuplicateCheckResult {
  /** Is potential duplicate */
  isDuplicate: boolean;
  
  /** Duplicate record IDs if found */
  duplicateIds: string[];
  
  /** Similarity score (0-1) */
  similarityScore: number;
  
  /** Reason for duplicate determination */
  reason: string;
}

/**
 * Final Transaction Record to Create
 */
export interface FinalTransactionRecord {
  /** User ID */
  userId: string;
  
  /** Transaction type */
  type: TransactionType;
  
  /** Amount */
  amount: number;
  
  /** Account ID */
  accountId: string;
  
  /** Category ID (optional for auto-generated) */
  categoryId?: string;
  
  /** Destination account (for transfers) */
  toAccountId?: string;
  
  /** Transaction date */
  transactionDate: Date;
  
  /** Notes/description */
  notes: string;
  
  /** Source type metadata */
  sourceMetadata: {
    source: SourceType;
    sourceId: string;
    platform: Platform;
    confidence: number;
    autoGenerated: true;
  };
  
  /** Reference for deduplication */
  deduplicationHash: string;
}

/**
 * Ingestion Result
 */
export interface IngestionResult {
  /** Success status */
  success: boolean;
  
  /** Created record ID if successful */
  recordId?: string;
  
  /** Error message if failed */
  error?: string;
  
  /** Reason for failure/success */
  reason: string;
  
  /** Original message for reference */
  messageId: string;
  
  /** Processing metadata */
  metadata: Record<string, any>;
}

/**
 * Ingestion Settings
 */
export interface IngestionSettings {
  /** Enable/disable auto-detection */
  autoDetectionEnabled: boolean;
  
  /** Minimum confidence threshold (0-1) */
  confidenceThreshold: number;
  
  /** Enable Android SMS */
  androidSmsEnabled: boolean;
  
  /** Enable notifications */
  notificationsEnabled: boolean;
  
  /** Enable email parsing */
  emailParsingEnabled: boolean;
  
  /** Enable manual scan */
  manualScanEnabled: boolean;
  
  /** Auto-categorize transactions */
  autoCategoryEnabled: boolean;
  
  /** Debug mode */
  debugMode: boolean;
  
  /** Banks configuration */
  bankConfigurations: BankConfiguration[];
}

/**
 * Bank Configuration for Pattern Matching
 */
export interface BankConfiguration {
  /** Bank identifier */
  id: string;
  
  /** Bank name */
  name: string;
  
  /** Sender identifiers (phone numbers, app names) */
  senderIdentifiers: string[];
  
  /** Transaction patterns */
  patterns: TransactionPattern[];
  
  /** Currency */
  currency: string;
  
  /** Active status */
  active: boolean;
}

/**
 * Transaction Pattern for Detection
 */
export interface TransactionPattern {
  /** Pattern name */
  name: string;
  
  /** Regex pattern */
  pattern: string | RegExp;
  
  /** Intent this pattern indicates */
  intent: TransactionIntent;
  
  /** Field extraction rules */
  fieldExtraction: FieldExtractionRule[];
  
  /** Minimum confidence for this pattern */
  minimumConfidence: number;
  
  /** Active status */
  active: boolean;
}

/**
 * Field Extraction Rule
 */
export interface FieldExtractionRule {
  /** Field name */
  field: keyof ExtractedTransactionData;
  
  /** Regex group or extractor */
  extractor: string | ((match: RegExpMatchArray) => any);
  
  /** Value transformer */
  transform?: (value: any) => any;
  
  /** Required field */
  required: boolean;
}

/**
 * Deduplication Rule
 */
export interface DeduplicationRule {
  /** Amount tolerance (±) */
  amountTolerance: number;
  
  /** Time window (milliseconds) */
  timeWindow: number;
  
  /** Require matching account */
  requireAccountMatch: boolean;
  
  /** Require matching provider */
  requireProviderMatch: boolean;
}

/**
 * Processing Pipeline State
 */
export interface PipelineState {
  /** Current stage */
  stage: 'ingestion' | 'normalization' | 'detection' | 'extraction' | 'classification' | 'deduplication' | 'persistence';
  
  /** Message being processed */
  message: UnifiedMessage | NormalizedMessage | TransactionCandidate;
  
  /** Processing errors */
  errors: string[];
  
  /** Processing warnings */
  warnings: string[];
  
  /** Metadata */
  metadata: Record<string, any>;
}
