/**
 * Transaction Classification Engine
 * Maps detected transactions to income/expense/transfer and suggests categories
 */

import {
    TransactionCandidate,
    TransactionClassification,
    TransactionIntent,
    TransactionType,
} from '../types';

/**
 * Category Mapping
 */
interface CategoryMapping {
  keywords: string[];
  category: string;
  categoryId: string;
  confidence: number;
}

/**
 * Transaction Classification Engine
 */
export class TransactionClassificationEngine {
  private categoryMappings: CategoryMapping[] = [];

  constructor(categoryMappings: CategoryMapping[] = []) {
    this.categoryMappings = [
      ...this.getDefaultCategoryMappings(),
      ...categoryMappings,
    ];
  }

  /**
   * Classify a transaction candidate
   */
  classify(candidate: TransactionCandidate): TransactionClassification {
    const transactionType = this.mapIntentToType(candidate.intent);
    const categoryMatch = this.suggestCategory(
      candidate.message.cleanText,
      candidate.extractedData.description || '',
      transactionType
    );

    return {
      type: transactionType,
      suggestedCategoryId: categoryMatch?.categoryId || null,
      categoryName: categoryMatch?.category || null,
      confidence: categoryMatch?.confidence || 0.5,
      isAutoGenerated: true,
      metadata: {
        originalIntent: candidate.intent,
        bankProvider: candidate.extractedData.bankOrProvider,
        source: candidate.message.sourceType,
      },
    };
  }

  /**
   * Map transaction intent to type
   */
  private mapIntentToType(intent: TransactionIntent): TransactionType {
    switch (intent) {
      case 'Credit':
        return 'income';
      case 'Debit':
        return 'expense';
      case 'Transfer':
        return 'transfer';
      default:
        return 'expense';
    }
  }

  /**
   * Suggest category based on text and transaction type
   */
  private suggestCategory(
    messageText: string,
    description: string,
    transactionType: TransactionType
  ): CategoryMapping | null {
    const searchText = `${messageText} ${description}`.toLowerCase();

    let bestMatch: CategoryMapping | null = null;
    let bestScore = 0;

    for (const mapping of this.categoryMappings) {
      // Filter by transaction type compatibility
      if (!this.isCompatibleWithType(mapping.categoryId, transactionType)) {
        continue;
      }

      let score = 0;
      let matches = 0;

      for (const keyword of mapping.keywords) {
        if (searchText.includes(keyword.toLowerCase())) {
          score += mapping.confidence;
          matches++;
        }
      }

      if (matches > 0) {
        const avgScore = score / mapping.keywords.length;
        if (avgScore > bestScore) {
          bestScore = avgScore;
          bestMatch = mapping;
        }
      }
    }

    return bestMatch;
  }

  /**
   * Check if category is compatible with transaction type
   */
  private isCompatibleWithType(categoryId: string, transactionType: TransactionType): boolean {
    // Income/Expense categories match their respective types
    // Transfer is a special case that doesn't have specific categories
    if (transactionType === 'transfer') {
      return categoryId === 'transfer';
    }

    if (transactionType === 'income') {
      return [
        'salary',
        'freelance',
        'interest',
        'refund',
        'investment_income',
        'bonus',
        'other_income',
      ].includes(categoryId);
    }

    if (transactionType === 'expense') {
      return ![
        'salary',
        'freelance',
        'interest',
        'refund',
        'investment_income',
        'bonus',
        'other_income',
        'transfer',
      ].includes(categoryId);
    }

    return true;
  }

  /**
   * Get default category mappings
   */
  private getDefaultCategoryMappings(): CategoryMapping[] {
    return [
      // Income Categories
      {
        keywords: ['salary', 'payment', 'credited', 'deposit'],
        category: 'Salary',
        categoryId: 'salary',
        confidence: 0.9,
      },
      {
        keywords: ['freelance', 'project', 'invoice', 'service'],
        category: 'Freelance',
        categoryId: 'freelance',
        confidence: 0.8,
      },
      {
        keywords: ['interest', 'dividend', 'return'],
        category: 'Interest/Investment',
        categoryId: 'interest',
        confidence: 0.85,
      },
      {
        keywords: ['refund', 'return', 'reversal'],
        category: 'Refund',
        categoryId: 'refund',
        confidence: 0.85,
      },

      // Expense Categories
      {
        keywords: ['food', 'restaurant', 'coffee', 'lunch', 'dinner', 'breakfast'],
        category: 'Food & Dining',
        categoryId: 'food',
        confidence: 0.85,
      },
      {
        keywords: ['grocery', 'supermarket', 'market', 'provisions'],
        category: 'Groceries',
        categoryId: 'groceries',
        confidence: 0.9,
      },
      {
        keywords: ['transport', 'taxi', 'uber', 'cab', 'bus', 'train', 'travel', 'ticket'],
        category: 'Transportation',
        categoryId: 'transport',
        confidence: 0.85,
      },
      {
        keywords: ['movie', 'cinema', 'entertainment', 'game', 'spotify', 'netflix', 'prime'],
        category: 'Entertainment',
        categoryId: 'entertainment',
        confidence: 0.8,
      },
      {
        keywords: ['utility', 'electric', 'power', 'water', 'gas', 'bill'],
        category: 'Utilities',
        categoryId: 'utilities',
        confidence: 0.85,
      },
      {
        keywords: ['medical', 'doctor', 'pharmacy', 'hospital', 'health', 'medicine'],
        category: 'Healthcare',
        categoryId: 'healthcare',
        confidence: 0.85,
      },
      {
        keywords: ['shopping', 'mall', 'store', 'retail', 'amazon', 'flipkart', 'purchase'],
        category: 'Shopping',
        categoryId: 'shopping',
        confidence: 0.75,
      },
      {
        keywords: ['rent', 'accommodation', 'house', 'flat', 'lease'],
        category: 'Rent',
        categoryId: 'rent',
        confidence: 0.9,
      },
      {
        keywords: ['internet', 'mobile', 'phone', 'data', 'airtel', 'jio', 'vodafone'],
        category: 'Mobile/Internet',
        categoryId: 'mobile',
        confidence: 0.85,
      },
      {
        keywords: ['subscription', 'membership', 'plan'],
        category: 'Subscriptions',
        categoryId: 'subscription',
        confidence: 0.75,
      },
      {
        keywords: ['fitness', 'gym', 'sport', 'yoga'],
        category: 'Fitness',
        categoryId: 'fitness',
        confidence: 0.8,
      },
      {
        keywords: ['education', 'course', 'learning', 'tuition', 'school'],
        category: 'Education',
        categoryId: 'education',
        confidence: 0.8,
      },
      {
        keywords: ['transfer', 'sent', 'payment to'],
        category: 'Transfer',
        categoryId: 'transfer',
        confidence: 0.85,
      },
    ];
  }

  /**
   * Add custom category mapping
   */
  addCategoryMapping(mapping: CategoryMapping): void {
    this.categoryMappings.push(mapping);
  }

  /**
   * Update category mappings (e.g., from backend)
   */
  updateCategoryMappings(mappings: CategoryMapping[]): void {
    this.categoryMappings = mappings;
  }

  /**
   * Get category by ID
   */
  getCategoryById(categoryId: string): CategoryMapping | null {
    return this.categoryMappings.find(m => m.categoryId === categoryId) || null;
  }
}

export const classificationEngine = new TransactionClassificationEngine();
